# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="My collection of data and analysis"
REPO_LICENSE=""
REPO_TOPICS="data-analysis,data-visualization"

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/data-curated.git"
REPO_WEB_URL="https://github.com/chicks-net/data-curated"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="data-curated"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "data-analysis"
    "data-visualization"
)
